baseurl = "https://www.zoocowski.com"
title = "home"

theme = "coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[permalinks]
    posts = "posts/:title/"
    default = ":title/"

[params]
    author = "Zoo Cow Ski"
    description = "Musings from a Simple Mooman"
    keywords = "notes,manager,leader,personal"
    info = "Some notes I have kept for myself"

#[[params.social]]
#    name = "Github"
#    weight = 1
#    url = "https://github.com/szukalski/"
[[params.social]]
    name = "LinkedIn"
    weight = 1
    url = "https://www.linkedin.com/in/davidjamesroberts/"
#[[params.social]]
#    name = "CV"
#    weight = 3
#    url = "docs/David.James.Roberts.CV.2018-03.16.pdf"

#[[menu.main]]
#    name = "Blog"
#    weight = 1
#    url  = "/blog/"
[[menu.main]]
    name = "career"
    weight = 2
    url = "/career/"
[[menu.main]]
    name = "management"
    weight = 3
    url = "/management/"
[[menu.main]]
    name = "finance"
    weight = 4
    url = "/finance/"
[[menu.main]]
    name = "routine"
    weight = 5
    url = "/routine/"
[[menu.main]]
    name = "About"
    weight = 6
    url = "/about/"